name: Verify Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example/tauri-app
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              libgtk-3-dev \
              libwebkit2gtk-4.1-dev \
              libappindicator3-dev \
              librsvg2-dev \
              patchelf \
              libgdk3.0-cil \
              libgdk-pixbuf2.0-dev \
              libsoup-3.0-dev
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      
      - uses: Swatinem/rust-cache@v2
      
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: tauri-cli@2.2.4  
        
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check
        run: cargo check --all-features

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Destkop
        run: cargo tauri build --no-bundle --ci
